export const ESPECIALIDADES_LISTA = [
  "URGENCIAS", "ANESTESIOLOGÍA", "CARDIOLOGÍA", "CIRUGÍA CARDIOTORÁCICA",
  "CIRUGÍA DE GASTROENTEROLOGÍA", "CIRUGÍA GENERAL", "CIRUGÍA NEUROLÓGICA",
  "CIRUGÍA PEDIÁTRICA", "CIRUGÍA PLÁSTICA ESTÉTICA Y RECONSTRUCTIVA",
  "CIRUGÍA VASCULAR Y ANGIOLOGÍA", "DERMATOLOGÍA", "ESPECIALIDADES ODONTOLÓGICAS",
  "GASTROENTEROLOGÍA", "GINECOLOGÍA Y OBSTETRICIA", "HEMATOLOGÍA",
  "MEDICINA CRÍTICA-TERAPIA INTENSIVA", "MEDICINA GENERAL", "MEDICINA INTERNA",
  "NEFROLOGÍA", "NEONATOLOGÍA", "NEUMOLOGÍA", "NEUROLOGÍA",
  "ODONTOLOGÍA GENERAL", "OFTALMOLOGÍA", "ONCOLOGÍA", "OTORRINOLARINGOLOGÍA",
  "PEDIATRÍA", "PSIQUIATRÍA", "REUMATOLOGÍA",
  "SERVICIOS AUXILIARES DE DIAGNÓSTICO Y TRATAMIENTO",
  "TRAUMATOLOGÍA Y ORTOPEDIA", "UROLOGÍA", "OTROS"
];

export const MOTIVOS_CATALOGO = {
  "TRATAMIENTO MÉDICO": ["ACCIDENTES E INCIDENTES", "COMPLICACIONES SECUNDARIAS", "DESINFORMACIÓN SOBRE EL TRATAMIENTO", "FALTA DE CONSENTIMIENTO", "RETRASO DEL TRATAMIENTO", "SECUELAS: EXCESO TERAPEUTICO", "TRATAMIENTO INADECUADO O INNECESARIO", "TRATAMIENTO INSATISFACTORIO", "OTRO (ESPECIFIQUE)"],
  "TRATAMIENTO QUIRÚRGICO": ["ACCIDENTES E INCIDENTES", "ALTA PREMATURA DE LOS CIUDADANOS POSTOPERATORIOS", "CIRUGIA INNECESARIA", "COMPLICACIONES QUIRÚRGICAS DEL POST OPERATORIO", "COMPLICACIONES QUIRÚRGICAS DEL TRANS OPERATORIO", "ERROR QUIRÚRGICO", "FALTA DE CARETA DE CONOCIMIENTO INFORMATIVO", "FALTA DE SEGUIMIENTO O SEGUIMIENTO INADECUADO EN EL POSTOPERATORIO", "FALTA DE VALORACION PRE QUIRÚRGICA", "RETRASO DEL TRATAMIENTO QUIRÚRGICO", "SECUELAS", "TECNICA QUIRÚRGICA INADECUADA", "TRATAMIENTO QUIRÚRGICO NO SATISFACTORIO", "OTRO (ESPECIFIQUE)"],
  "DEFICIENCIAS ADMINISTRATIVAS": ["CAMBIO DE MÉDICO TRATANTE O DE UNIDAD MÉDICA", "DEMORA PROLONGADA Y/O DIFERIMENTO PARA OBTENER EL SERVICIO", "FALTA DE EQUIPO MEDICO", "FALTA DE INSUMOS O MEDICAMENTOS", "FALTA DE PERSONAL", "NEGACIÓN DE LA ATENCIÓN", "SISTEMA DE REFERENCIA Y CONTRAREFERENCIA", "TRATO INADECUADO POR PARTE DEL PERSONAL ADMINISTRATIVO", "OTRO (ESPECIFIQUE)"],
  "AUXILIARES DE DIAGNOSTICO Y TRATAMIENTO": ["COMPLICACIONES SECUNDARIAS DE LOS PROCEDIMIENTOS DIAGNÓSTICOS", "ESTUDIOS INNECESARIOS", "FALSOS POSITIVOS O NEGATIVOS", "FALTA DE INFORMACIÓN Y CONOCIMIENTO", "RETRASO DEL PROCEDIMIENTO DIAGNÓSTICO", "RETRASO O FALTA DE NOTIFICACIÓN DE RESULTADOS", "SECUELAS", "OTRO (ESPECIFIQUE)"],
  "DIAGNÓSTICO": ["DESINFORMACIÓN SOBRE EL DIAGNÓSTICO", "DIAGNÓSTICO ERRÓNEO", "OMISION DEL DIAGNOSTICO", "RETRASO DEL DIAGNÓSTICO", "OTRO (ESPECIFIQUE)"],
  "RELACIÓN MÉDICO PACIENTE": ["FALLAS EN LA COMUNICACION", "TRATAMIENTO INADECUADO", "FALSAS EXPECTATIVAS", "OTRO (ESPECIFIQUE)"]
};

export const ESTATUS_SIREMED_OPCIONES = ["PENDIENTE", "SUBIDO"];